name: Fireguard
services: 
  api:
    container_name: "api-service"
    ports: 
      - "8080:8080"
      - "5272:5272"
    build: 
      dockerfile: Api/Api/Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      #;https://+:5272
  database: 
    container_name: "database-service"
    build: 
      context: . 
      dockerfile: Database/Database/Dockerfile
    environment:
      - ConnectionStrings__Psql=${PSQL_CONNECTION_STRING}
      - ASPNETCORE_URLS=http://+:5000
      #;https://+:5001
    depends_on:
      db:
        condition: service_started
  db:
    container_name: "psql-db"
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=devpass
  python:
    container_name: "python-risk-service"
    build:
      context: ./Python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MET_CLIENT_ID: ${MET_CLIENT_ID}
      MET_CLIENT_SECRET: ${MET_CLIENT_SECRET}

    
