name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore .NET dependencies
        run: dotnet restore ./Api/Api/Api/Api.csproj

      - name: Build .NET project
        run: dotnet build ./Api/Api/Api/Api.csproj --configuration Release

      - name: Run .NET tests
        run: dotnet test ./Api/Api.Tests/Api.Tests.csproj --configuration Release

  build-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        working-directory: ./Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python tests
        working-directory: ./Python
        run: |
          pytest

  docker-build:
    runs-on: ubuntu-latest
    needs: [build-dotnet, build-python]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build
      # Optionally, push Docker images to a registry

